service: product-service
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}

functions:
  getProducts:
    handler: handler.getProducts
    events:
      - http:
         path: /products
         method: get
         cors: true 
  getProduct:
    handler: handler.getProduct
    events:
      - http:
         path: /products/{id}
         method: get
         cors: true 
  addProduct:
    handler: handler.addProduct
    events:
      - http:
         path: /products
         method: post
         cors: true 
